#!/usr/bin/env bash
## BP010: Release metadata
## @build_type: lib
## @build_date: 2026-03-20T07:44:01Z
set -e
use() { return 0; }
extern() { return 0; }
legacy() { return 0; }
module() { return 0; }
public() { return 0; }
embed() { return 0; }
inject() { return 0; }
## BP004: Compile the entrypoint


#extern package cavalla

#echo "A1"
embed handler
#handler
#echo "A2"

__breakpoint() {
  echo "Debug"
}

__plugin_debugger__feature_debug__hook_debug_entrypoint_init() {
  #handler
  echo "#trap '__debug_trap_handler' DEBUG"
}


#  echo "> $BASH_COMMAND"
#  echo "  $BASH_SOURCE : $LINENO"

handler() {
  if [ -z "$1" ]; then
    cat <<'EMBED'
__debug_trap_handler() {
  echo "A: $LINENO $BASH_COMMAND"
}
EMBED
  else
    case "$1" in
      *)
        echo ": "
        ;;
    esac
  fi
}
